import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { resolve } from "node:path";

const require = createRequire(import.meta.url);
const { generatorHandler } = require("@prisma/generator-helper") as typeof import("@prisma/generator-helper");

function generatedModule(metadata: unknown): string {
  return `// Generated by @kavo/prisma. Do not edit.\nexport const prismaMetadata = ${JSON.stringify(metadata, null, 2)} as const;\n\nexport default prismaMetadata;\n`;
}

generatorHandler({
  onManifest() {
    return {
      defaultOutput: "./generated/kavo-metadata.ts",
      prettyName: "Kavo Prisma metadata",
    };
  },
  async onGenerate(options) {
    const output = options.generator.output?.value;
    if (output === null || output === undefined) {
      throw new Error("@kavo/prisma requires an output path for generated metadata");
    }

    const outputPath = resolve(output);
    await mkdir(resolve(outputPath, ".."), { recursive: true });
    await writeFile(outputPath, generatedModule(options.dmmf.datamodel), "utf8");
  },
});
