import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import type { PrismaField, PrismaMetadata } from "./datamodel.js";

const require = createRequire(import.meta.url);
const { generatorHandler } = require("@prisma/generator-helper") as typeof import("@prisma/generator-helper");

/** The TS type of one field's value, ignoring list/nullable — see {@link tsFieldType}. */
function scalarTsType(field: PrismaField): string {
  if (field.kind === "object") {
    // A relation: the field's own type name is the target model, which the
    // generated module declares a class for under the same name.
    return field.type;
  }
  if (field.kind === "enum") {
    // The generated module declares a union type under the enum's own name.
    return field.type;
  }
  switch (field.type) {
    case "Int":
    case "Float":
    case "BigInt":
    case "Decimal":
      return "number";
    case "Boolean":
      return "boolean";
    case "DateTime":
      return "Date";
    case "Json":
      return "unknown";
    default:
      return "string";
  }
}

/**
 * A field's full TS type, matching the shape the hand-written marker
 * classes used to declare by hand: `T[]` for a list (never nullable — an
 * empty list, not null, is Prisma's absence value for a to-many relation),
 * `T | null` for an optional scalar or to-one relation, plain `T` otherwise.
 */
function tsFieldType(field: PrismaField): string {
  const base = scalarTsType(field);
  if (field.isList) {
    return `${base}[]`;
  }
  return field.isRequired ? base : `${base} | null`;
}

/**
 * The generated module's content: `prismaMetadata` as before, plus one
 * marker class per DMMF model (typed field-for-field, so `filter`/`sort`/
 * `include` config keeps compile-time checking) and a ready-made `entities`
 * array built from them — so an app wires
 * `createPrismaKavo(prisma, { metadata, entities })` straight from
 * `prisma generate` output instead of hand-declaring a marker class per
 * model (issue #459). `createInfrastructure`'s `entities` option is
 * unchanged — a caller who wants their own marker classes (for
 * `instanceof`/DI use elsewhere) can still pass their own array.
 */
export function generatedModule(metadata: PrismaMetadata): string {
  const enumDeclarations = metadata.enums
    .map(
      (prismaEnum) =>
        `export type ${prismaEnum.name} = ${
          prismaEnum.values.length > 0
            ? prismaEnum.values.map((value) => JSON.stringify(value.name)).join(" | ")
            : "never"
        };`,
    )
    .join("\n");

  const classDeclarations = metadata.models
    .map((model) => {
      const fields = model.fields.map((field) => `  ${field.name}!: ${tsFieldType(field)};`).join("\n");
      return (
        `export class ${model.name} {\n${fields}\n}\n` +
        // A bundler's production minification (e.g. Next.js's SWC minify)
        // renames classes — @kavo/prisma matches a marker class to its
        // Prisma model by the class's runtime `name` (ADR-0017), so pin it
        // to a string literal, which survives minification.
        `Object.defineProperty(${model.name}, "name", { value: ${JSON.stringify(model.name)} });`
      );
    })
    .join("\n\n");

  const entityNames = metadata.models.map((model) => model.name).join(", ");

  return (
    `// Generated by @kavo/prisma. Do not edit.\n` +
    `export const prismaMetadata = ${JSON.stringify(metadata, null, 2)} as const;\n\n` +
    `export default prismaMetadata;\n\n` +
    `${enumDeclarations}${enumDeclarations.length > 0 ? "\n\n" : ""}` +
    `${classDeclarations}\n\n` +
    `export const entities = [${entityNames}] as const;\n`
  );
}

generatorHandler({
  onManifest() {
    return {
      defaultOutput: "./generated/kavo-metadata.ts",
      prettyName: "Kavo Prisma metadata",
    };
  },
  async onGenerate(options) {
    const output = options.generator.output?.value;
    if (output === null || output === undefined) {
      throw new Error("@kavo/prisma requires an output path for generated metadata");
    }

    const outputPath = resolve(output);
    await mkdir(resolve(outputPath, ".."), { recursive: true });
    await writeFile(outputPath, generatedModule(options.dmmf.datamodel as unknown as PrismaMetadata), "utf8");
  },
});
