import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import * as barrel from "@kavo/core";

/**
 * The public surface of `@kavo/core`, as a manifest.
 *
 * ADR-0010 makes the barrel a deliberate explicit named list so the public
 * surface "changes only on purpose", and a future api-extractor gate
 * will diff against it. Until that gate exists nothing detects an export
 * added or removed by accident — a stray `export` in an unrelated commit
 * is invisible in review once the diff is long enough.
 *
 * Kept as an inline list rather than a vitest snapshot on purpose: a
 * snapshot invites `-u`, which turns an intentional-by-design change into
 * a reflex. Adding a name here should cost a moment's thought.
 *
 * Type-only exports erase at runtime, so the manifest is checked against
 * the *source* of the barrel — `import * as` would see barely a third of
 * it. The last test pins the runtime half against the same list, catching
 * what source-parsing cannot: a name the barrel claims but cannot resolve.
 */
const PUBLIC_SURFACE: readonly string[] = [
  "AlreadyDeletedException",
  "ArrayMutationAction",
  "ArrayMutationHandlerFactories",
  "ArrayMutationInvalidShapeException",
  "ArrayMutationMemberNotFoundException",
  "ArrayMutationRelationEntry",
  "ArrayMutationSettings",
  "ArrayMutationStrategy",
  "AuthorizationSettings",
  "BUILT_IN_DEFAULTS",
  "CacheSettings",
  "CacheStore",
  "EtagSettings",
  "CatalogedErrorCode",
  "ClassRef",
  "ComputedFieldDescriptor",
  "ComputedFieldMap",
  "ConfigurationException",
  "ConflictException",
  "CustomOperationBody",
  "CustomOperationConfig",
  "CustomOperationId",
  "CustomOperationRequest",
  "CustomOperationResult",
  "KavoCallOptions",
  "KavoContext",
  "KavoContextInit",
  "KavoContextState",
  "KavoEngine",
  "KavoEngineDependencies",
  "KavoExceptionShape",
  "KavoInfrastructure",
  "KavoRequest",
  "KavoResponse",
  "KavoRuntime",
  "KavoService",
  "KavoErrorCode",
  "KavoException",
  "KavoExceptionOptions",
  "KavoInstance",
  "KavoOptions",
  "KavoSettings",
  "DeepPartial",
  "DefaultKavoContextState",
  "DefaultKavoService",
  "DefaultDeserializer",
  "DefaultDtoResolver",
  "DefaultEntityCatalog",
  "DefaultErrorHandler",
  "DefaultFilterParser",
  "DefaultIncludeResolver",
  "DefaultOperationRegistry",
  "DefaultRelationRegistry",
  "DefaultSerializer",
  "addRelationOperationId",
  "listRelationOperationId",
  "registerArrayMutationOperations",
  "removeRelationOperationId",
  "replaceRelationOperationId",
  "writeOptedInRelationNames",
  "DeleteStrategy",
  "Deserializer",
  "Dto",
  "DtoClass",
  "DtoInputOf",
  "DtoOutputOf",
  "DtoQueryOf",
  "DtoResolver",
  "DtoSlot",
  "ERROR_CATALOG",
  "EntityCatalog",
  "EntityConfig",
  "EntityId",
  "EntityInput",
  "EntityMetadata",
  "EntityReader",
  "EntityRuntimeInfo",
  "EntityWriter",
  "ErrorCatalogEntry",
  "ErrorContext",
  "ErrorHandler",
  "ErrorSettings",
  "FieldKind",
  "FieldMetadata",
  "FieldPath",
  "FieldPathDepth",
  "FieldSelection",
  "FieldSelectionInput",
  "Filter",
  "FilterBuilder",
  "FilterCondition",
  "FilterExpression",
  "FilterGroup",
  "FilterOperator",
  "FilterParser",
  "FilterScalar",
  "FilterValue",
  "FindManyResult",
  "ForbiddenException",
  "GlobalConfig",
  "HARD_DELETE",
  "IdentifiedWrite",
  "IncludeNode",
  "IncludeRequest",
  "IncludePath",
  "IncludeResolver",
  "IncludeTree",
  "IsAny",
  "IsUnknown",
  "JsonPatchInvalidDocumentException",
  "JsonPatchTargetNotFoundException",
  "KavoPrincipal",
  "PolicyNode",
  "cursorValuesOf",
  "encodeCursor",
  "evaluateFilter",
  "isCursorPagination",
  "isSincePagination",
  "hasKeyset",
  "readFilter",
  "sinceValueOf",
  "CursorPagination",
  "CursorPaginationStrategy",
  "SincePaginationStrategy",
  "ListMetaContributor",
  "ListMetaDto",
  "ListResultDto",
  "LogicalOperator",
  "MetadataSource",
  "NONE_PAGINATION_LIMIT",
  "NonePaginationStrategy",
  "NormalizedQueryContext",
  "NotDeletedException",
  "NotFoundException",
  "OffsetPagination",
  "OffsetPaginationStrategy",
  "OperationCardinality",
  "OperationConfig",
  "OperationDescriptor",
  "OperationDisabledException",
  "OperationNotRegisteredException",
  "OperationDtoMap",
  "OperationDtoOverride",
  "OperationHandler",
  "OperationId",
  "OperationKind",
  "OperationMetadata",
  "OperationRegistry",
  "OperationsConfig",
  "PagePaginationStrategy",
  "Pagination",
  "PaginationLimits",
  "PaginationSettings",
  "PaginationStrategy",
  "PaginationStrategyName",
  "PersistenceException",
  "PreconditionFailedException",
  "PreconditionUnsupportedException",
  "Primitive",
  "ProblemDetailsDto",
  "ProblemDetailsOptions",
  "QueryAllowlists",
  "QueryContext",
  "QueryFieldSelector",
  "QueryIssueDto",
  "QueryNormalizer",
  "QuerySettings",
  "QueryValidationException",
  "RealtimeEventDto",
  "RealtimeEventId",
  "RealtimeFieldSelector",
  "RealtimeSettings",
  "RealtimeTransport",
  "RelationCardinality",
  "RelationDescriptor",
  "RelationEdgeSettings",
  "RelationFieldSelector",
  "RelationLoadStrategy",
  "RelationRegistry",
  "RelationSettings",
  "RepositoryAdapter",
  "RequestPreconditions",
  "ResolvedEntityConfig",
  "ResolvedQueryAllowlists",
  "ResolvedSoftDelete",
  "STANDARD_OPERATIONS",
  "ScalarKeys",
  "SearchDriver",
  "SearchMode",
  "SearchSettings",
  "Serializer",
  "SincePagination",
  "SoftDeletable",
  "SoftDeleteMode",
  "SoftDeleteSettings",
  "Sort",
  "SortDirection",
  "StandardHandlerFactory",
  "StandardOperationId",
  "StandardOperationsConfig",
  "StateKey",
  "TransactionContext",
  "TransactionException",
  "TransactionManager",
  "TransactionOptions",
  "TransactionPropagation",
  "WhenParams",
  "WhenPredicateArgs",
  "WireQuery",
  "and",
  "assertNever",
  "authenticated",
  "builtInHandlers",
  "builtInPaginationStrategies",
  "computeEtag",
  "createCrud",
  "createKavo",
  "createKavoContext",
  "isEtagEnabled",
  "createMemoryCacheStore",
  "createOperationRegistry",
  "deepFreeze",
  "describeResolvedConfig",
  "dtoShapeKeys",
  "evaluatePolicy",
  "filtered",
  "mergeSettings",
  "not",
  "or",
  "owner",
  "parseBracketKey",
  "permission",
  "policyNeedsEntity",
  "renderMessage",
  "resolveEntityConfig",
  "resolveSoftDelete",
  "role",
  "toProblemDetails",
  "validateSettings",
  "when",
  "withListMeta",
];

/** Export names in the barrel source, both `export type` and value forms. */
function exportedNames(): string[] {
  const source = readFileSync(new URL("../src/index.ts", import.meta.url), "utf8")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/[^\n]*/g, "");
  const names: string[] = [];
  for (const match of source.matchAll(/export\s+(?:type\s+)?\{([^}]*)\}\s*from/g)) {
    for (const raw of (match[1] ?? "").split(",")) {
      const name = raw.trim().replace(/^type\s+/, "");
      if (name.length > 0) names.push(name.includes(" as ") ? (name.split(" as ").pop() as string).trim() : name);
    }
  }
  return names;
}

describe("@kavo/core public surface (ADR-0010)", () => {
  it("exports exactly the manifest", () => {
    expect([...exportedNames()].sort()).toEqual([...PUBLIC_SURFACE].sort());
  });

  it("names each export once", () => {
    const names = exportedNames();
    expect(names).toHaveLength(new Set(names).size);
  });

  it("resolves every runtime export the manifest claims", () => {
    // Guards the half source-parsing cannot see: a name listed in the
    // barrel that does not actually resolve at runtime.
    const runtime = Object.keys(barrel).sort();
    expect(runtime.filter((name) => !PUBLIC_SURFACE.includes(name))).toEqual([]);
    expect(runtime.length).toBeGreaterThan(0);
  });
});
